name: Actions Workflow

on:
  # schedule:
  # Run each 5 minutes
  # - cron: "0/5 * * * *"

  # Add trigger from url
  repository_dispatch:
    types: [build]
  push:
    branches:
      - master
      - "feature/*"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      # Get and show payload info from body in request
      - name: Get payload
        run: echo ${{ github.event.client_payload.env }}

      # Show files before checkout
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      # Checkout on current commit
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # Show files after checkout
      - name: List Files after checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        continue-on-error: false
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rober
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
