name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        continue-on-error: false
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Rober
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
