name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.3-alpine3.9
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
